force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <defaultValue>&quot;INV0&quot;</defaultValue>
    <label>Invoice Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Total__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Total__c</fullName>
    <formula>Subtotal__c +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <summarizedField>Invoice_Line_Item__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_amount__c</fullName>
    <formula>Tax_rate__c *  Subtotal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_rate__c</fullName>
    <defaultValue>0.3</defaultValue>
    <label>Tax rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>Subtotal__c *  VAT_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <defaultValue>0.2</defaultValue>
    <label>VAT Rate</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Description_of_expense__c.field-meta.xml
<CustomField>
    <fullName>Description_of_expense__c</fullName>
    <description>Describe the nature of the expense</description>
    <label>Description of expense</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustController.cls
public class CustController {


 private final Invoice__c account;

        public CustController() { 
        
       account = [SELECT Id, 		Invoice_Date__c, 	Invoice_Owner__c, Invoice_Number__c, RecordTypeId, Course__c, 	Tax_rate__c, 	
            VAT__c, 	Subtotal__c, Name, 	VAT_Total__c,
            VAT_Rate__c, Tax_amount__c, 	Invoice_Total__c
    
    
            FROM Invoice__c 
            where Id = : ApexPages.currentPage().getParameters().get('id')];
            
   
    }
    
     
    public Invoice__c getInvoices() {
        return account;
    }
 
    public PageReference save() {
        update account;
        return null;
    
    }
    
         public static List<Invoice_Line_Item__c> getlineItems() {
             List<Invoice_Line_Item__c> results = [
                 SELECT Id, 	Amount__c, 	Description_of_expense__c, 	Date__c, Invoice__c, Name, VAT__c, Total_Amount__c
                 FROM Invoice_Line_Item__c 
                 where Invoice__c = :ApexPages.currentPage().getParameters().get('id')
             ];
           return results;
        }
    
        }
   
     
    
    
    